alias gti='git'
#alias tmux='tmux -2'
alias less='less -R'
alias diff='colordiff'
alias dc='cd'
alias nethack-online='ssh nethack@nethack.alt.org ; clear'
alias tron-online='ssh sshtron.zachlatta.com ; clear'
alias glog='git log --oneline --graph --color --all --decorate'
alias pbcopy='xclip -sel clip'
alias bye='/home/brian/.bye'
alias balena='/home/brian/.balena'
alias finances='libreoffice /home/brian/Documents/finances/financials.ods'
alias droidcam-update='/home/brian/.droidcam_update'
alias gpom='git push origin main'
alias gph='git push heroku'
alias gc='git add . && git commit -m'
alias gs='git status'
alias parsec='parsecd app_daemon=1'
alias hgpu='watch nvidia-smi'
alias homelab_vpn="sudo wg-quick up homelab"
alias homelab_vpn_off="sudo wg-quick down homelab"
alias bonsai_vpn="sudo wg-quick up bonsai"
alias bonsai_vpn_off="sudo wg-quick down bonsai"
alias pqsl="psql"
alias musescore="~/Programs/MuseScore-4.0.2.230651545-x86_64.AppImage"
alias tf="terraform"
alias tfi="terraform init"
alias tfp="terraform plan"
alias tfa="terraform apply"
alias tfd="terraform destroy"
alias tfs="terraform show -json | jq"
alias tfo="terraform output -json | jq"
alias tfg="terraform graph | dot -Tpdf"
alias myip="curl ifconfig.co"
alias via="via-nativia"
