alias gti='git'
#alias tmux='tmux -2'
alias less='less -R'
alias diff='colordiff'
alias dc='cd'
alias nethack-online='ssh nethack@nethack.alt.org ; clear'
alias tron-online='ssh sshtron.zachlatta.com ; clear'
alias glog='git log --oneline --graph --color --all --decorate'
alias pbcopy='xclip sel clip'
alias pivssh='ssh -A -o PKCS11Provider=/usr/lib/ssh-keychain.dylib'
alias addpiv='ssh-add -e /usr/lib/ssh-keychain.dylib 2>/dev/null;ssh-add -s /usr/lib/ssh-keychain.dylib;ssh-add ~/.ssh/id_rsa'
alias lamsweb='/usr/local/bin/lamsweb'
