alias gti='git'
#alias tmux='tmux -2'
alias less='less -R'
alias diff='colordiff'
alias dc='cd'
alias nethack-online='ssh nethack@nethack.alt.org ; clear'
alias tron-online='ssh sshtron.zachlatta.com ; clear'
alias glog='git log --oneline --graph --color --all --decorate'
alias pbcopy='xclip -sel clip'
alias bye='/home/brian/.bye'
alias balena='/home/brian/.balena'
alias finances='libreoffice /home/brian/Documents/finances/financials.ods'
alias droidcam-update='/home/brian/.droidcam_update'
alias gpo='git push origin'
alias gph='git push heroku'
alias parsec='parsecd app_daemon=1'
alias hgpu='watch nvidia-smi'
